const jobsData = [
  // --- AI & DATA ---
  {
    "id": 1,
    "title": "AI Prompt Engineer",
    "category": "AI & Data",
    "icon": "fa-solid fa-robot",
    "salary": "45,000 - 120,000",
    "desc": "ผู้เชี่ยวชาญด้านการสื่อสารกับ AI เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด",
    "long_desc": "ในฐานะ AI Prompt Engineer คุณเปรียบเสมือนล่ามภาษามนุษย์สู่ภาษาจักรกล คุณไม่ได้แค่พิมพ์คำสั่ง แต่คุณต้องเข้าใจโครงสร้างตรรกะของ Large Language Models (LLMs) เพื่อออกแบบชุดคำสั่ง (Prompts) ที่ซับซ้อน ปรับจูนพารามิเตอร์ และสร้าง Workflow ที่ทำให้ AI สามารถทำงานแทนมนุษย์ได้อย่างแม่นยำ",
    "responsibilities": ["ออกแบบและทดสอบ Prompt", "สร้าง Library ของ Prompt มาตรฐาน", "ลด Hallucination ของ AI", "จูนระบบ AI ร่วมกับ Dev"],
    "education": "ไม่จำกัดวุฒิ แต่ต้องมี Logic ดีเยี่ยม",
    "skills": ["NLP Understanding", "Linguistics", "Critical Thinking"],
    "tools": ["ChatGPT Plus", "Midjourney", "Claude AI"],
    "mode": "Remote 100%",
    "growth": "สูงสุด (High Demand)"
  },
  {
    "id": 2,
    "title": "Data Scientist",
    "category": "AI & Data",
    "icon": "fa-solid fa-chart-pie",
    "salary": "50,000 - 150,000",
    "desc": "นักวิทยาศาสตร์ข้อมูลผู้วิเคราะห์แนวโน้มเพื่อขับเคลื่อนธุรกิจ",
    "long_desc": "เปลี่ยนข้อมูลดิบมหาศาลให้กลายเป็นขุมทรัพย์ทางธุรกิจ ใช้คณิตศาสตร์ สถิติ และการเขียนโปรแกรม เพื่อทำความสะอาดข้อมูล สร้างโมเดล Machine Learning ทำนายอนาคต (Predictive Analytics)",
    "responsibilities": ["Data Cleaning", "สร้างโมเดล Machine Learning", "ทำ Data Visualization", "A/B Testing"],
    "education": "สถิติ, คณิตศาสตร์, CS",
    "skills": ["Statistics", "Machine Learning", "Data Storytelling"],
    "tools": ["Python", "SQL", "Tableau", "TensorFlow"],
    "mode": "Hybrid",
    "growth": "มั่นคงมาก"
  },
  {
    "id": 3,
    "title": "AI Ethicist",
    "category": "AI & Data",
    "icon": "fa-solid fa-scale-balanced",
    "salary": "60,000 - 130,000",
    "desc": "ผู้ดูแลจริยธรรม AI ป้องกันความลำเอียงและผลกระทบต่อสังคม",
    "long_desc": "ตรวจสอบอัลกอริทึมว่ามีการเหยียดเพศ เชื้อชาติ หรือละเมิดความเป็นส่วนตัวหรือไม่ พร้อมทั้งร่างนโยบายการใช้ AI ภายในองค์กรให้สอดคล้องกับกฎหมายและหลักมนุษยธรรม",
    "responsibilities": ["ตรวจสอบ Bias ใน Dataset", "ร่าง Guideline การใช้ AI", "Compliance PDPA/GDPR"],
    "education": "นิติศาสตร์, ปรัชญา, สังคมวิทยา",
    "skills": ["Ethics", "AI Governance", "Risk Assessment"],
    "tools": ["AI Audit Tools", "Policy Docs"],
    "mode": "Hybrid",
    "growth": "เติบโตในองค์กรใหญ่"
  },
  {
    "id": 4,
    "title": "Machine Learning Engineer",
    "category": "AI & Data",
    "icon": "fa-solid fa-brain",
    "salary": "60,000 - 180,000",
    "desc": "วิศวกรผู้สร้างสมองของ AI ให้เรียนรู้และทำงานได้จริง",
    "long_desc": "โฟกัสที่การนำโมเดล Data Science ไปขึ้นระบบจริง (Production) ออกแบบ Architecture ให้ AI ประมวลผลได้รวดเร็ว รองรับผู้ใช้งานจำนวนมาก และดูแลระบบให้เสถียร",
    "responsibilities": ["Deploy ML Model", "Scale ระบบ AI", "Optimize Model Performance"],
    "education": "Computer Science, Computer Engineering",
    "skills": ["Python/C++", "System Design", "Cloud Computing"],
    "tools": ["AWS SageMaker", "Docker", "PyTorch"],
    "mode": "Remote / Hybrid",
    "growth": "สูงมาก"
  },

  // --- SOFTWARE ---
  {
    "id": 5,
    "title": "DevOps Engineer",
    "category": "Software",
    "icon": "fa-solid fa-infinity",
    "salary": "60,000 - 160,000",
    "desc": "ผู้ประสานรอยต่อระหว่างการเขียนโค้ดและการดูแลระบบ",
    "long_desc": "ทำให้กระบวนการส่งมอบซอฟต์แวร์เป็นอัตโนมัติ (Automation) ตั้งแต่การเขียนโค้ด ทดสอบ ไปจนถึงการปล่อยขึ้น Server จริง ดูแล Infrastructure บน Cloud",
    "responsibilities": ["สร้าง CI/CD Pipeline", "ดูแล Cloud Infrastructure", "Monitor Server Health"],
    "education": "Computer Engineering, IT",
    "skills": ["CI/CD", "Cloud Architecture", "Scripting"],
    "tools": ["Docker", "Kubernetes", "Jenkins", "AWS"],
    "mode": "Remote",
    "growth": "ขาดแคลนหนัก"
  },
  {
    "id": 6,
    "title": "Full Stack Developer",
    "category": "Software",
    "icon": "fa-solid fa-layer-group",
    "salary": "40,000 - 140,000",
    "desc": "นักพัฒนาเว็บที่ทำได้ครบจบในคนเดียวทั้งหน้าบ้านและหลังบ้าน",
    "long_desc": "เข้าใจโครงสร้าง Web Application ทั้งระบบ ตั้งแต่หน้าจอ (Frontend) ฐานข้อมูล (Database) และ API (Backend) สามารถขึ้นโปรเจกต์ได้ด้วยตัวคนเดียว",
    "responsibilities": ["เขียน Frontend (React/Vue)", "เขียน API (Node/Go)", "ออกแบบ Database"],
    "education": "CS หรือ Bootcamp",
    "skills": ["JavaScript", "Database Design", "API Dev"],
    "tools": ["React", "Node.js", "PostgreSQL", "Git"],
    "mode": "Remote Friendly",
    "growth": "เป็นที่ต้องการเสมอ"
  },
  {
    "id": 7,
    "title": "Cloud Architect",
    "category": "Software",
    "icon": "fa-solid fa-cloud",
    "salary": "80,000 - 200,000",
    "desc": "สถาปนิกผู้ออกแบบโครงสร้างระบบบน Cloud",
    "long_desc": "ออกแบบวางแผนว่าองค์กรจะใช้ Cloud Service ตัวไหน (AWS, Azure, GCP) เพื่อให้ประหยัดงบที่สุด ปลอดภัยที่สุด และรองรับผู้ใช้งานได้มากที่สุด",
    "responsibilities": ["ออกแบบ Cloud Strategy", "คำนวณ Cost", "ดูแล Cloud Security"],
    "education": "Computer Engineering, IT",
    "skills": ["Cloud Services", "System Arch", "Networking"],
    "tools": ["AWS", "Azure", "Terraform"],
    "mode": "Hybrid",
    "growth": "สูงตามการใช้ Cloud"
  },
  {
    "id": 8,
    "title": "Blockchain Developer",
    "category": "Software",
    "icon": "fa-solid fa-link",
    "salary": "70,000 - 200,000",
    "desc": "นักพัฒนาโลกไร้ศูนย์กลางและ Smart Contract",
    "long_desc": "เขียนโปรแกรมบนระบบ Blockchain (Smart Contracts) สร้าง DApps (Decentralized Apps) หรือระบบการเงินแบบใหม่ (DeFi) ที่มีความปลอดภัยสูงและตรวจสอบได้",
    "responsibilities": ["เขียน Smart Contract", "Audit ความปลอดภัย Code", "เชื่อมต่อ Web3"],
    "education": "CS, Cryptography",
    "skills": ["Solidity", "Rust", "Cryptography"],
    "tools": ["Ethereum", "Hardhat", "Metamask"],
    "mode": "Remote 100%",
    "growth": "เฉพาะทาง รายได้สูง"
  },
  {
    "id": 9,
    "title": "Game Developer",
    "category": "Software",
    "icon": "fa-solid fa-gamepad",
    "salary": "35,000 - 100,000",
    "desc": "ผู้สร้างความบันเทิงในโลกเสมือนจริง",
    "long_desc": "เขียนโค้ดเพื่อควบคุมกลไกของเกม (Game Physics, AI ศัตรู, ระบบคะแนน) ทำงานร่วมกับ Artist และ Designer เพื่อสร้างประสบการณ์การเล่นที่ลื่นไหล",
    "responsibilities": ["เขียน Gameplay Logic", "Optimize กราฟิก", "แก้ Bug เกม"],
    "education": "CS, Game Dev, Multimedia",
    "skills": ["C#", "C++", "3D Math"],
    "tools": ["Unity", "Unreal Engine", "Blender"],
    "mode": "On-site / Hybrid",
    "growth": "เติบโตตามอุตสาหกรรมเกม"
  },

  // --- CREATIVE ---
  {
    "id": 10,
    "title": "Generative AI Artist",
    "category": "Creative",
    "icon": "fa-solid fa-wand-magic-sparkles",
    "salary": "35,000 - 100,000",
    "desc": "ศิลปินยุคใหม่ที่ใช้ AI เป็นพู่กันสร้างสรรค์ผลงาน",
    "long_desc": "ผสมผสานรสนิยมทางศิลปะ (Artistic Sense) เข้ากับเทคนิคการใช้เครื่องมือ AI เพื่อผลิตชิ้นงานภาพประกอบ กราฟิก หรือวิดีโอที่สวยงาม รวดเร็ว และตอบโจทย์ลูกค้า",
    "responsibilities": ["Generate ภาพด้วย AI", "Retouch งานให้สมบูรณ์", "คิด Concept Art"],
    "education": "ศิลปกรรม, นิเทศศิลป์",
    "skills": ["Art Direction", "Composition", "Image Editing"],
    "tools": ["Midjourney", "Stable Diffusion", "Photoshop"],
    "mode": "Freelance / Remote",
    "growth": "กำลังมาแรง"
  },
  {
    "id": 11,
    "title": "UX/UI Designer",
    "category": "Creative",
    "icon": "fa-solid fa-pen-nib",
    "salary": "35,000 - 90,000",
    "desc": "นักออกแบบประสบการณ์ผู้ใช้ ให้แอปฯ ใช้งานง่าย",
    "long_desc": "ทำ User Research เข้าใจปัญหา แล้วนำมาออกแบบเป็น Wireframe และหน้าจอที่สวยงาม (UI) เน้นความง่ายในการใช้งาน (Usability)",
    "responsibilities": ["User Research", "ออกแบบ Wireframe/Prototype", "ทำ UI Design System"],
    "education": "Design, HCI, Psychology",
    "skills": ["Empathy", "Visual Design", "Prototyping"],
    "tools": ["Figma", "Adobe XD", "Maze"],
    "mode": "Hybrid",
    "growth": "สำคัญมาก"
  },
  {
    "id": 12,
    "title": "AR/VR Developer",
    "category": "Creative",
    "icon": "fa-solid fa-vr-cardboard",
    "salary": "50,000 - 120,000",
    "desc": "ผู้สร้างโลกเสมือนจริงและโลกผสานความจริง",
    "long_desc": "พัฒนาแอปพลิเคชันสำหรับแว่น VR (Virtual Reality) หรือระบบ AR (Augmented Reality) บนมือถือ สำหรับงานเกม การแพทย์ หรือการฝึกอบรมเสมือนจริง",
    "responsibilities": ["สร้างสภาพแวดล้อม 3D", "เขียน Interactive Logic", "Optimize Performance"],
    "education": "Multimedia, CS",
    "skills": ["3D Modeling", "Spatial Computing", "C#"],
    "tools": ["Unity 3D", "Spark AR", "Blender"],
    "mode": "Hybrid",
    "growth": "เติบโตตามเทรนด์ Metaverse"
  },

  // --- BUSINESS ---
  {
    "id": 13,
    "title": "Digital Marketing Manager",
    "category": "Business",
    "icon": "fa-solid fa-bullhorn",
    "salary": "50,000 - 120,000",
    "desc": "นักวางแผนกลยุทธ์การตลาดในโลกออนไลน์",
    "long_desc": "วางแผนว่าจะยิงโฆษณาที่ไหน (Facebook, TikTok, Google) จะทำคอนเทนต์อะไร และวัดผล ROI อย่างไร เพื่อสร้างยอดขายให้บริษัท",
    "responsibilities": ["วางแผนกลยุทธ์", "ยิง Ads", "วิเคราะห์ Data หลังบ้าน"],
    "education": "การตลาด, บริหารธุรกิจ",
    "skills": ["Data Analytics", "Content Strategy", "Budgeting"],
    "tools": ["Google Analytics", "Meta Ads", "TikTok Ads"],
    "mode": "Hybrid",
    "growth": "สูง (ทุกธุรกิจต้องมี)"
  },
  {
    "id": 14,
    "title": "Tech Product Owner",
    "category": "Business",
    "icon": "fa-solid fa-list-check",
    "salary": "70,000 - 150,000",
    "desc": "เจ้าของผลิตภัณฑ์ ผู้กำหนดทิศทางแอปพลิเคชัน",
    "long_desc": "คนกลางระหว่างทีม Business และทีม Dev จัดลำดับความสำคัญ (Prioritization) ว่าฟีเจอร์ไหนควรทำก่อน-หลัง เพื่อให้สินค้าตอบโจทย์ลูกค้าที่สุด",
    "responsibilities": ["เก็บ Requirement", "เขียน User Stories", "จัดลำดับ Backlog"],
    "education": "MBA, IT Management",
    "skills": ["Agile/Scrum", "Communication", "Decision Making"],
    "tools": ["Jira", "Trello", "Miro"],
    "mode": "Hybrid",
    "growth": "บทบาทผู้นำ"
  },
  {
    "id": 15,
    "title": "E-Commerce Manager",
    "category": "Business",
    "icon": "fa-solid fa-shop",
    "salary": "40,000 - 100,000",
    "desc": "ผู้จัดการร้านค้าออนไลน์ครบวงจร",
    "long_desc": "ดูแลยอดขายบน Platform (Shopee, Lazada, Web) วางแผนโปรโมชั่น จัดการสต็อก และดูแลทีม Customer Service ให้ลูกค้าประทับใจ",
    "responsibilities": ["วางแผน Campaign", "จัดการ Stock", "วิเคราะห์ยอดขายรายวัน"],
    "education": "บริหารธุรกิจ, โลจิสติกส์",
    "skills": ["Sales Strategy", "Platform Mgmt", "Customer Service"],
    "tools": ["Shopee/Lazada Seller", "ERP", "Excel"],
    "mode": "Hybrid",
    "growth": "โตตามตลาดออนไลน์"
  },
  {
    "id": 16,
    "title": "Fintech Specialist",
    "category": "Business",
    "icon": "fa-solid fa-coins",
    "salary": "50,000 - 130,000",
    "desc": "ผู้เชี่ยวชาญเทคโนโลยีทางการเงิน",
    "long_desc": "วิเคราะห์และพัฒนาผลิตภัณฑ์ทางการเงินรูปแบบใหม่ (Digital Banking, Wallet, Payment Gateway) ให้สอดคล้องกับพฤติกรรมผู้ใช้และกฎระเบียบ",
    "responsibilities": ["วิเคราะห์ Product การเงิน", "ประสานงานทีม Tech", "ดูแล Compliance"],
    "education": "การเงิน, เศรษฐศาสตร์, IT",
    "skills": ["Finance Knowledge", "Tech Savvy", "Regulations"],
    "tools": ["Banking Systems", "Excel Model"],
    "mode": "Hybrid",
    "growth": "สูง (Bank กำลังปรับตัว)"
  },

  // --- SECURITY ---
  {
    "id": 17,
    "title": "Cyber Security Analyst",
    "category": "Security",
    "icon": "fa-solid fa-shield-halved",
    "salary": "50,000 - 120,000",
    "desc": "ผู้พิทักษ์ระบบคอมพิวเตอร์จากการถูกโจมตี",
    "long_desc": "เฝ้าระวัง Monitor Log และสัญญาณเตือนภัยต่างๆ ว่ามีแฮกเกอร์พยายามเจาะระบบหรือไม่ พร้อมทั้งติดตั้ง Firewall/Antivirus และวางแผนรับมือ",
    "responsibilities": ["เฝ้าระวัง (SOC)", "วิเคราะห์ช่องโหว่", "สืบสวน Forensics"],
    "education": "Computer Engineering, Cybersecurity",
    "skills": ["Network Security", "Incident Response", "OS"],
    "tools": ["Splunk", "Wireshark", "Nessus"],
    "mode": "On-site (Secure Room)",
    "growth": "ขาดแคลนหนักมาก"
  },
  {
    "id": 18,
    "title": "Penetration Tester",
    "category": "Security",
    "icon": "fa-solid fa-user-secret",
    "salary": "60,000 - 150,000",
    "desc": "แฮกเกอร์สายขาว ผู้ทดสอบเจาะระบบเพื่อหาจุดอ่อน",
    "long_desc": "ได้รับอนุญาตให้จำลองการโจมตี (Ethical Hacking) เพื่อหาช่องโหว่ของเว็บไซต์หรือแอปพลิเคชัน ก่อนที่แฮกเกอร์ตัวจริงจะเจอ",
    "responsibilities": ["เจาะระบบ (Pentest)", "เขียนรายงานช่องโหว่", "แนะนำวิธีปิดช่องโหว่"],
    "education": "CS, IT, Certifications (OSCP)",
    "skills": ["Ethical Hacking", "Scripting", "Report Writing"],
    "tools": ["Kali Linux", "Burp Suite", "Metasploit"],
    "mode": "Hybrid",
    "growth": "รายได้สูง ค่าตัวแพง"
  },

  // --- HEALTH ---
  {
    "id": 19,
    "title": "Health Tech Developer",
    "category": "Health",
    "icon": "fa-solid fa-heart-pulse",
    "salary": "45,000 - 120,000",
    "desc": "นักพัฒนาเทคโนโลยีเพื่อสุขภาพ",
    "long_desc": "สร้างแอปพลิเคชัน Telemedicine ระบบนัดหมอออนไลน์ หรือเชื่อมต่อข้อมูลจาก Smart Watch เข้าสู่ระบบของแพทย์ เพื่อให้การดูแลสุขภาพทั่วถึง",
    "responsibilities": ["พัฒนา Health App", "เชื่อมต่อ IoT (นาฬิกา)", "ดูแล Privacy ข้อมูลคนไข้"],
    "education": "Biomedical Eng, CS",
    "skills": ["Mobile Dev", "Data Privacy", "Health Standards"],
    "tools": ["Flutter", "HealthKit", "Firebase"],
    "mode": "Hybrid",
    "growth": "เติบโตตามสังคมผู้สูงอายุ"
  },
  {
    "id": 20,
    "title": "Bioinformatics Scientist",
    "category": "Health",
    "icon": "fa-solid fa-dna",
    "salary": "60,000 - 140,000",
    "desc": "นักชีวสารสนเทศ วิเคราะห์รหัสพันธุกรรมด้วยคอมพิวเตอร์",
    "long_desc": "ใช้ความรู้ด้านชีววิทยาและโปรแกรมมิ่ง เพื่อวิเคราะห์ข้อมูล DNA/RNA ขนาดใหญ่ ช่วยในการคิดค้นยารักษาโรคหรือวัคซีนใหม่ๆ",
    "responsibilities": ["วิเคราะห์ข้อมูลพันธุกรรม", "เขียน Script ประมวลผล", "ทำ Data Model ชีวภาพ"],
    "education": "Bioinformatics, Biology, CS",
    "skills": ["Biology", "Python/R", "Statistics"],
    "tools": ["BLAST", "Biopython", "Linux"],
    "mode": "Lab / Office",
    "growth": "เฉพาะทางมาก"
  },
  
  // --- OTHERS (Future) ---
  {
    "id": 21,
    "title": "IoT Specialist",
    "category": "Software",
    "icon": "fa-solid fa-wifi",
    "salary": "45,000 - 100,000",
    "desc": "ผู้เชี่ยวชาญ Internet of Things เชื่อมอุปกรณ์เข้าสู่เน็ต",
    "long_desc": "ออกแบบระบบ Smart Home หรือ Smart Factory ให้อุปกรณ์ต่างๆ (Sensor, กล้อง, เครื่องจักร) คุยกันได้ผ่านอินเทอร์เน็ต",
    "responsibilities": ["ออกแบบวงจร/Sensor", "เขียน Firmware", "เชื่อมต่อ Cloud MQTT"],
    "education": "Electronic Eng, Computer Eng",
    "skills": ["Electronics", "Microcontroller", "Networking"],
    "tools": ["Arduino", "Raspberry Pi", "MQTT"],
    "mode": "On-site / Lab",
    "growth": "มาแรงในโรงงานอุตสาหกรรม"
  },
  {
    "id": 22,
    "title": "Robotics Engineer",
    "category": "AI & Data",
    "icon": "fa-solid fa-hand-holding-hand",
    "salary": "50,000 - 120,000",
    "desc": "วิศวกรหุ่นยนต์ สร้างเครื่องจักรทำงานแทนคน",
    "long_desc": "ออกแบบและโปรแกรมหุ่นยนต์แขนกล (Robot Arm) ในโรงงาน หรือหุ่นยนต์บริการ ให้เคลื่อนที่และทำงานได้อย่างแม่นยำ",
    "responsibilities": ["ออกแบบกลไกหุ่นยนต์", "เขียนโปรแกรมควบคุม (ROS)", "Maintain ระบบ"],
    "education": "Mechatronics, Mechanical Eng",
    "skills": ["Mechanics", "Control Theory", "Programming"],
    "tools": ["ROS", "SolidWorks", "C++"],
    "mode": "On-site",
    "growth": "ต้องการสูงใน EEC"
  }
];