const jobsData = [
  // --- AI และข้อมูล ---
  {
    "id": 1,
    "title": "วิศวกรออกแบบคำสั่งปัญญาประดิษฐ์ (AI Prompt Engineer)",
    "category": "AI และข้อมูล",
    "icon": "fa-solid fa-robot",
    "salary": "45,000 - 120,000",
    "desc": "ผู้เชี่ยวชาญด้านการสื่อสารกับ AI เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด",
    "long_desc": "ในฐานะวิศวกรออกแบบคำสั่ง AI คุณเปรียบเสมือนล่ามภาษามนุษย์สู่ภาษาจักรกล คุณไม่ได้แค่พิมพ์คำสั่ง แต่คุณต้องเข้าใจโครงสร้างตรรกะของ Large Language Models (LLMs) เพื่อออกแบบชุดคำสั่ง (Prompts) ที่ซับซ้อน ปรับจูนพารามิเตอร์ และสร้าง Workflow ที่ทำให้ AI สามารถทำงานแทนมนุษย์ได้อย่างแม่นยำ",
    "responsibilities": ["ออกแบบและทดสอบคำสั่ง Prompt", "สร้างคลังข้อมูล Prompt มาตรฐาน", "ลดความผิดพลาด (Hallucination) ของ AI", "ปรับปรุงระบบ AI ร่วมกับทีมพัฒนา"],
    "education": "ไม่จำกัดวุฒิการศึกษา (พิจารณาจากทักษะด้านตรรกะและการสื่อสารเป็นหลัก)",
    "skills": ["การเข้าใจภาษาธรรมชาติ (NLP)", "ภาษาศาสตร์", "การคิดเชิงวิพากษ์"],
    "tools": ["ChatGPT Plus", "Midjourney", "Claude AI"],
    "mode": "ทำงานทางไกล 100% (Remote)",
    "growth": "ความต้องการสูงมาก (High Demand)",
    "image": "https://www.nstda.or.th/opr/wp-content/uploads/2023/04/digitalai.png",
    "reference": "https://www.google.com/search?q=AI+Prompt+Engineer+Job+Description"
  },
  {
    "id": 2,
    "title": "นักวิทยาศาสตร์ข้อมูล (Data Scientist)",
    "category": "AI และข้อมูล",
    "icon": "fa-solid fa-chart-pie",
    "salary": "50,000 - 150,000",
    "desc": "นักวิทยาศาสตร์ข้อมูลผู้วิเคราะห์แนวโน้มเพื่อขับเคลื่อนธุรกิจ",
    "long_desc": "เปลี่ยนข้อมูลดิบมหาศาลให้กลายเป็นขุมทรัพย์ทางธุรกิจ ใช้คณิตศาสตร์ สถิติ และการเขียนโปรแกรม เพื่อทำความสะอาดข้อมูล สร้างโมเดล Machine Learning ทำนายอนาคต (Predictive Analytics)",
    "responsibilities": ["ทำความสะอาดข้อมูล", "สร้างโมเดลการเรียนรู้ของเครื่อง", "นำเสนอข้อมูลด้วยภาพ", "การทดสอบสมมติฐาน (A/B Testing)"],
    "education": "ปริญญาตรีหรือปริญญาโท สาขาสถิติ, คณิตศาสตร์ หรือวิทยาการคอมพิวเตอร์",
    "skills": ["สถิติ", "การเรียนรู้ของเครื่อง (Machine Learning)", "การเล่าเรื่องจากข้อมูล"],
    "tools": ["Python", "SQL", "Tableau", "TensorFlow"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "มั่นคงมาก",
    "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    "reference": "https://www.google.com/search?q=Data+Scientist+Career+Path"
  },
  {
    "id": 3,
    "title": "ผู้เชี่ยวชาญด้านจริยธรรม AI (AI Ethicist)",
    "category": "AI และข้อมูล",
    "icon": "fa-solid fa-scale-balanced",
    "salary": "60,000 - 130,000",
    "desc": "ผู้ดูแลจริยธรรม AI ป้องกันความลำเอียงและผลกระทบต่อสังคม",
    "long_desc": "ตรวจสอบอัลกอริทึมว่ามีการเหยียดเพศ เชื้อชาติ หรือละเมิดความเป็นส่วนตัวหรือไม่ พร้อมทั้งร่างนโยบายการใช้ AI ภายในองค์กรให้สอดคล้องกับกฎหมายและหลักมนุษยธรรม",
    "responsibilities": ["ตรวจสอบความลำเอียงในชุดข้อมูล", "ร่างแนวทางปฏิบัติการใช้ AI", "ดูแลความสอดคล้องกับกฎหมาย PDPA/GDPR"],
    "education": "ปริญญาตรี สาขานิติศาสตร์, ปรัชญา หรือสังคมวิทยา",
    "skills": ["จริยธรรม", "การกำกับดูแล AI", "การประเมินความเสี่ยง"],
    "tools": ["เครื่องมือตรวจสอบ AI", "เอกสารนโยบาย"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "เติบโตในองค์กรขนาดใหญ่",
    "image": "https://www.salika.co/wp-content/uploads/2024/07/AI-ethical-concept-businessman-artificial-1024x538.jpg",
    "reference": "https://www.google.com/search?q=AI+Ethicist+Roles"
  },
  {
    "id": 4,
    "title": "วิศวกร Machine Learning",
    "category": "AI และข้อมูล",
    "icon": "fa-solid fa-brain",
    "salary": "60,000 - 180,000",
    "desc": "วิศวกรผู้สร้างสมองของ AI ให้เรียนรู้และทำงานได้จริง",
    "long_desc": "โฟกัสที่การนำโมเดล Data Science ไปขึ้นระบบจริง (Production) ออกแบบ Architecture ให้ AI ประมวลผลได้รวดเร็ว รองรับผู้ใช้งานจำนวนมาก และดูแลระบบให้เสถียร",
    "responsibilities": ["ติดตั้งโมเดล ML ขึ้นระบบ", "ขยายขนาดระบบ AI", "ปรับปรุงประสิทธิภาพของโมเดล"],
    "education": "ปริญญาตรี สาขาวิศวกรรมคอมพิวเตอร์ หรือวิทยาการคอมพิวเตอร์",
    "skills": ["Python/C++", "การออกแบบระบบ", "ระบบคลาวด์"],
    "tools": ["AWS SageMaker", "Docker", "PyTorch"],
    "mode": "ทำงานทางไกล หรือ ผสมผสาน",
    "growth": "สูงมาก",
    "image": "https://aigencorp.com/wp-content/uploads/2023/06/1-1-1024x683.jpg",
    "reference": "https://www.google.com/search?q=Machine+Learning+Engineer+Skills"
  },

  // --- ซอฟต์แวร์ ---
  {
    "id": 5,
    "title": "วิศวกรเดฟออปส์ (DevOps Engineer)",
    "category": "ซอฟต์แวร์",
    "icon": "fa-solid fa-infinity",
    "salary": "60,000 - 160,000",
    "desc": "ผู้ประสานรอยต่อระหว่างการเขียนโค้ดและการดูแลระบบ",
    "long_desc": "ทำให้กระบวนการส่งมอบซอฟต์แวร์เป็นอัตโนมัติ (Automation) ตั้งแต่การเขียนโค้ด ทดสอบ ไปจนถึงการปล่อยขึ้น Server จริง ดูแล Infrastructure บน Cloud",
    "responsibilities": ["สร้างระบบ CI/CD Pipeline", "ดูแลโครงสร้างระบบคลาวด์", "ตรวจสอบสถานะเครื่องแม่ข่าย"],
    "education": "ปริญญาตรี สาขาวิศวกรรมคอมพิวเตอร์ หรือเทคโนโลยีสารสนเทศ (IT)",
    "skills": ["CI/CD", "โครงสร้างคลาวด์", "การเขียนสคริปต์"],
    "tools": ["Docker", "Kubernetes", "Jenkins", "AWS"],
    "mode": "ทำงานทางไกล (Remote)",
    "growth": "ขาดแคลนบุคลากรอย่างหนัก",
    "image": "https://tse2.mm.bing.net/th/id/OIP.pJ0T0jQK3Tdp1ndZ1tvFkQAAAA?rs=1&pid=ImgDetMain&o=7&rm=3",
    "reference": "https://www.google.com/search?q=DevOps+Engineer+Roadmap"
  },
  {
    "id": 6,
    "title": "นักพัฒนา Full Stack (Full Stack Developer)",
    "category": "ซอฟต์แวร์",
    "icon": "fa-solid fa-layer-group",
    "salary": "40,000 - 140,000",
    "desc": "นักพัฒนาเว็บที่ทำได้ครบจบในคนเดียวทั้งหน้าบ้านและหลังบ้าน",
    "long_desc": "เข้าใจโครงสร้าง Web Application ทั้งระบบ ตั้งแต่หน้าจอ (Frontend) ฐานข้อมูล (Database) และ API (Backend) สามารถขึ้นโปรเจกต์ได้ด้วยตัวคนเดียว",
    "responsibilities": ["พัฒนาส่วนหน้าบ้าน (React/Vue)", "พัฒนาส่วนหลังบ้าน (Node/Go)", "ออกแบบฐานข้อมูล"],
    "education": "ปริญญาตรี สาขาวิทยาการคอมพิวเตอร์ หรือผ่านหลักสูตรฝึกอบรมเร่งด่วน (Bootcamp)",
    "skills": ["JavaScript", "การออกแบบฐานข้อมูล", "การพัฒนา API"],
    "tools": ["React", "Node.js", "PostgreSQL", "Git"],
    "mode": "ทำงานทางไกลได้ (Remote Friendly)",
    "growth": "เป็นที่ต้องการของตลาดเสมอ",
    "image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
    "reference": "https://www.google.com/search?q=Full+Stack+Developer+Jobs"
  },
  {
    "id": 7,
    "title": "สถาปนิกคลาวด์ (Cloud Architect)",
    "category": "ซอฟต์แวร์",
    "icon": "fa-solid fa-cloud",
    "salary": "80,000 - 200,000",
    "desc": "สถาปนิกผู้ออกแบบโครงสร้างระบบบน Cloud",
    "long_desc": "ออกแบบวางแผนว่าองค์กรจะใช้ Cloud Service ตัวไหน (AWS, Azure, GCP) เพื่อให้ประหยัดงบที่สุด ปลอดภัยที่สุด และรองรับผู้ใช้งานได้มากที่สุด",
    "responsibilities": ["วางกลยุทธ์ระบบคลาวด์", "คำนวณต้นทุนการใช้งาน", "ดูแลความปลอดภัยบนคลาวด์"],
    "education": "ปริญญาตรี สาขาวิศวกรรมคอมพิวเตอร์ หรือเทคโนโลยีสารสนเทศ (IT)",
    "skills": ["บริการคลาวด์", "สถาปัตยกรรมระบบ", "ระบบเครือข่าย"],
    "tools": ["AWS", "Azure", "Terraform"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "สูงตามอัตราการใช้ระบบคลาวด์",
    "image": "https://miro.medium.com/v2/resize:fit:1358/format:webp/1*AZzJTRTCWG-46x78f54CUg.png",
    "reference": "https://www.google.com/search?q=Cloud+Architect+Certification"
  },
  {
    "id": 8,
    "title": "นักพัฒนาบล็อกเชน (Blockchain Developer)",
    "category": "ซอฟต์แวร์",
    "icon": "fa-solid fa-link",
    "salary": "70,000 - 200,000",
    "desc": "นักพัฒนาโลกไร้ศูนย์กลางและ Smart Contract",
    "long_desc": "เขียนโปรแกรมบนระบบ Blockchain (Smart Contracts) สร้าง DApps (Decentralized Apps) หรือระบบการเงินแบบใหม่ (DeFi) ที่มีความปลอดภัยสูงและตรวจสอบได้",
    "responsibilities": ["เขียนสัญญาอัจฉริยะ (Smart Contract)", "ตรวจสอบความปลอดภัยของโค้ด", "เชื่อมต่อระบบ Web3"],
    "education": "ปริญญาตรี สาขาวิทยาการคอมพิวเตอร์ หรือสาขาที่เกี่ยวข้องกับวิทยาการรหัสลับ (Cryptography)",
    "skills": ["Solidity", "Rust", "วิทยาการรหัสลับ"],
    "tools": ["Ethereum", "Hardhat", "Metamask"],
    "mode": "ทำงานทางไกล 100% (Remote)",
    "growth": "อาชีพเฉพาะทางที่มีรายได้สูง",
    "image": "https://img.freepik.com/premium-photo/businessman-drawing-abstract-block-chain-hologram-blurry-office-background-cryptography-future-concept-double-exposure_670147-71163.jpg",
    "reference": "https://www.google.com/search?q=Blockchain+Developer+Salary"
  },
  {
    "id": 9,
    "title": "นักพัฒนาเกม (Game Developer)",
    "category": "ซอฟต์แวร์",
    "icon": "fa-solid fa-gamepad",
    "salary": "35,000 - 100,000",
    "desc": "ผู้สร้างความบันเทิงในโลกเสมือนจริง",
    "long_desc": "เขียนโค้ดเพื่อควบคุมกลไกของเกม (Game Physics, AI ศัตรู, ระบบคะแนน) ทำงานร่วมกับ Artist และ Designer เพื่อสร้างประสบการณ์การเล่นที่ลื่นไหล",
    "responsibilities": ["เขียนตรรกะการเล่นเกม", "ปรับปรุงประสิทธิภาพกราฟิก", "แก้ไขข้อผิดพลาดในเกม"],
    "education": "ปริญญาตรี สาขาวิทยาการคอมพิวเตอร์, การพัฒนาเกม หรือมัลติมีเดีย",
    "skills": ["C#", "C++", "คณิตศาสตร์ 3 มิติ"],
    "tools": ["Unity", "Unreal Engine", "Blender"],
    "mode": "หน้างาน หรือ แบบผสมผสาน",
    "growth": "เติบโตตามอุตสาหกรรมเกม",
    "image": "https://img.freepik.com/premium-photo/indian-male-game-designer-using-desktop-with-3d-modeling-software_1291600-6664.jpg",
    "reference": "https://www.google.com/search?q=Game+Developer+Jobs"
  },

  // --- สร้างสรรค์ ---
  {
    "id": 10,
    "title": "ศิลปิน Generative AI (Generative AI Artist)",
    "category": "สร้างสรรค์",
    "icon": "fa-solid fa-wand-magic-sparkles",
    "salary": "35,000 - 100,000",
    "desc": "ศิลปินยุคใหม่ที่ใช้ AI เป็นพู่กันสร้างสรรค์ผลงาน",
    "long_desc": "ผสมผสานรสนิยมทางศิลปะ (Artistic Sense) เข้ากับเทคนิคการใช้เครื่องมือ AI เพื่อผลิตชิ้นงานภาพประกอบ กราฟิก หรือวิดีโอที่สวยงาม รวดเร็ว และตอบโจทย์ลูกค้า",
    "responsibilities": ["สร้างภาพด้วย AI", "ตกแต่งผลงานให้สมบูรณ์", "คิดแนวคิดศิลปะ (Concept Art)"],
    "education": "ปริญญาตรี สาขาศิลปกรรมศาสตร์ หรือนิเทศศิลป์",
    "skills": ["การกำกับศิลป์", "องค์ประกอบภาพ", "การแต่งภาพ"],
    "tools": ["Midjourney", "Stable Diffusion", "Photoshop"],
    "mode": "อาชีพอิสระ หรือ ทำงานทางไกล",
    "growth": "กำลังเป็นกระแสที่มาแรง",
    "image": "https://tse2.mm.bing.net/th/id/OIP.GSU7lg72sEkWBWv2h2iY-AHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    "reference": "https://www.google.com/search?q=Generative+AI+Artist+Portfolio"
  },
  {
    "id": 11,
    "title": "นักออกแบบ UX/UI (UX/UI Designer)",
    "category": "สร้างสรรค์",
    "icon": "fa-solid fa-pen-nib",
    "salary": "35,000 - 90,000",
    "desc": "นักออกแบบประสบการณ์ผู้ใช้ ให้แอปฯ ใช้งานง่าย",
    "long_desc": "ทำ User Research เข้าใจปัญหา แล้วนำมาออกแบบเป็น Wireframe และหน้าจอที่สวยงาม (UI) เน้นความง่ายในการใช้งาน (Usability)",
    "responsibilities": ["วิจัยผู้ใช้งาน", "ออกแบบ Wireframe/ต้นแบบ", "สร้างระบบการออกแบบ UI"],
    "education": "ปริญญาตรี สาขาการออกแบบ, ปฏิสัมพันธ์ระหว่างมนุษย์และคอมพิวเตอร์ (HCI) หรือจิตวิทยา",
    "skills": ["ความเข้าใจผู้ใช้ (Empathy)", "การออกแบบภาพ", "การสร้างต้นแบบ"],
    "tools": ["Figma", "Adobe XD", "Maze"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "มีความสำคัญมากต่อทุกผลิตภัณฑ์ดิจิทัล",
    "image": "https://minio.launchplatform.co.th/uploads/article/57f3dedd-17b7-4550-9c1d-963d6b0f8b73/cover.webp",
    "reference": "https://www.google.com/search?q=UX+UI+Designer+Course"
  },
  {
    "id": 12,
    "title": "นักพัฒนา AR/VR (AR/VR Developer)",
    "category": "สร้างสรรค์",
    "icon": "fa-solid fa-vr-cardboard",
    "salary": "50,000 - 120,000",
    "desc": "ผู้สร้างโลกเสมือนจริงและโลกผสานความจริง",
    "long_desc": "พัฒนาแอปพลิเคชันสำหรับแว่น VR (Virtual Reality) หรือระบบ AR (Augmented Reality) บนมือถือ สำหรับงานเกม การแพทย์ หรือการฝึกอบรมเสมือนจริง",
    "responsibilities": ["สร้างสภาพแวดล้อม 3 มิติ", "เขียนตรรกะการโต้ตอบ", "ปรับปรุงประสิทธิภาพการทำงาน"],
    "education": "ปริญญาตรี สาขามัลติมีเดีย หรือวิทยาการคอมพิวเตอร์",
    "skills": ["การปั้นแบบ 3 มิติ", "Spatial Computing", "C#"],
    "tools": ["Unity 3D", "Spark AR", "Blender"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "เติบโตตามเทรนด์ Metaverse",
    "image": "https://tse3.mm.bing.net/th/id/OIP.wawtDjhI8jnatmj2Jah5pwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
    "reference": "https://www.google.com/search?q=AR+VR+Developer+Future"
  },

  // --- ธุรกิจ ---
  {
    "id": 13,
    "title": "ผู้จัดการการตลาดดิจิทัล (Digital Marketing Manager)",
    "category": "ธุรกิจ",
    "icon": "fa-solid fa-bullhorn",
    "salary": "50,000 - 120,000",
    "desc": "นักวางแผนกลยุทธ์การตลาดในโลกออนไลน์",
    "long_desc": "วางแผนว่าจะยิงโฆษณาที่ไหน (Facebook, TikTok, Google) จะทำคอนเทนต์อะไร และวัดผล ROI อย่างไร เพื่อสร้างยอดขายให้บริษัท",
    "responsibilities": ["วางแผนกลยุทธ์การตลาด", "บริหารการโฆษณา", "วิเคราะห์ข้อมูลเชิงลึก"],
    "education": "ปริญญาตรี สาขาการตลาด หรือบริหารธุรกิจ",
    "skills": ["การวิเคราะห์ข้อมูล", "กลยุทธ์เนื้อหา", "การบริหารงบประมาณ"],
    "tools": ["Google Analytics", "Meta Ads", "TikTok Ads"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "สูง (เป็นตำแหน่งที่ทุกธุรกิจต้องมี)",
    "image": "https://th.bing.com/th/id/R.adb9a98c2e118d3e71c86a8c1c3619a7?rik=JSnSgAyCyHmocw&pid=ImgRaw&r=0",
    "reference": "https://www.google.com/search?q=Digital+Marketing+Trends"
  },
  {
    "id": 14,
    "title": "เจ้าของผลิตภัณฑ์เทคโนโลยี (Tech Product Owner)",
    "category": "ธุรกิจ",
    "icon": "fa-solid fa-list-check",
    "salary": "70,000 - 150,000",
    "desc": "เจ้าของผลิตภัณฑ์ ผู้กำหนดทิศทางแอปพลิเคชัน",
    "long_desc": "คนกลางระหว่างทีม Business และทีม Dev จัดลำดับความสำคัญ (Prioritization) ว่าฟีเจอร์ไหนควรทำก่อน-หลัง เพื่อให้สินค้าตอบโจทย์ลูกค้าที่สุด",
    "responsibilities": ["รวบรวมความต้องการ", "เขียนรายละเอียดงาน (User Stories)", "จัดลำดับงานในคลังงาน"],
    "education": "ปริญญาโท สาขาบริหารธุรกิจ (MBA) หรือการจัดการเทคโนโลยีสารสนเทศ",
    "skills": ["Agile/Scrum", "การสื่อสาร", "การตัดสินใจ"],
    "tools": ["Jira", "Trello", "Miro"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "บทบาทผู้นำในสายงานเทคโนโลยี",
    "image": "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80",
    "reference": "https://www.google.com/search?q=Product+Owner+vs+Product+Manager"
  },
  {
    "id": 15,
    "title": "ผู้จัดการอีคอมเมิร์ซ (E-Commerce Manager)",
    "category": "ธุรกิจ",
    "icon": "fa-solid fa-shop",
    "salary": "40,000 - 100,000",
    "desc": "ผู้จัดการร้านค้าออนไลน์ครบวงจร",
    "long_desc": "ดูแลยอดขายบน Platform (Shopee, Lazada, Web) วางแผนโปรโมชั่น จัดการสต็อก และดูแลทีม Customer Service ให้ลูกค้าประทับใจ",
    "responsibilities": ["วางแผนแคมเปญการขาย", "จัดการสต็อกสินค้า", "วิเคราะห์ยอดขายรายวัน"],
    "education": "ปริญญาตรี สาขาบริหารธุรกิจ หรือการจัดการโลจิสติกส์",
    "skills": ["กลยุทธ์การขาย", "การจัดการแพลตฟอร์ม", "การบริการลูกค้า"],
    "tools": ["Shopee/Lazada Seller", "ERP", "Excel"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "เติบโตตามตลาดออนไลน์",
    "image": "https://img.freepik.com/premium-photo/shopping-online-hand-touching-online-shopping-with-virtual-graphic-icon-diagram-payment-online-digital-marketing-business-finance-internet-network-technology-concept_35148-7866.jpg",
    "reference": "https://www.google.com/search?q=E-commerce+Management+Tips"
  },
  {
    "id": 16,
    "title": "ผู้เชี่ยวชาญฟินเทค (Fintech Specialist)",
    "category": "ธุรกิจ",
    "icon": "fa-solid fa-coins",
    "salary": "50,000 - 130,000",
    "desc": "ผู้เชี่ยวชาญเทคโนโลยีทางการเงิน",
    "long_desc": "วิเคราะห์และพัฒนาผลิตภัณฑ์ทางการเงินรูปแบบใหม่ (Digital Banking, Wallet, Payment Gateway) ให้สอดคล้องกับพฤติกรรมผู้ใช้และกฎระเบียบ",
    "responsibilities": ["วิเคราะห์ผลิตภัณฑ์การเงิน", "ประสานงานกับทีมเทคนิค", "ดูแลความถูกต้องตามกฎระเบียบ"],
    "education": "ปริญญาตรี สาขาการเงิน, เศรษฐศาสตร์ หรือเทคโนโลยีสารสนเทศ (IT)",
    "skills": ["ความรู้ทางการเงิน", "ความเข้าใจเทคโนโลยี", "กฎระเบียบการเงิน"],
    "tools": ["ระบบธนาคาร", "การสร้างแบบจำลองใน Excel"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "สูง (ธุรกิจธนาคารกำลังปรับตัวอย่างมาก)",
    "image": "https://www.smartosc.com/wp-content/uploads/2023/12/fintech-service-e1703592968417.png",
    "reference": "https://www.google.com/search?q=Fintech+Trends+2026"
  },

  // --- ความปลอดภัย ---
  {
    "id": 17,
    "title": "นักวิเคราะห์ความปลอดภัยไซเบอร์ (Cyber Security Analyst)",
    "category": "ความปลอดภัย",
    "icon": "fa-solid fa-shield-halved",
    "salary": "50,000 - 120,000",
    "desc": "ผู้พิทักษ์ระบบคอมพิวเตอร์จากการถูกโจมตี",
    "long_desc": "เฝ้าระวัง Monitor Log และสัญญาณเตือนภัยต่างๆ ว่ามีแฮกเกอร์พยายามเจาะระบบหรือไม่ พร้อมทั้งติดตั้ง Firewall/Antivirus และวางแผนรับมือ",
    "responsibilities": ["การเฝ้าระวังภัยคุกคาม (SOC)", "วิเคราะห์ช่องโหว่ระบบ", "การสืบสวนร่องรอยดิจิทัล (Forensics)"],
    "education": "ปริญญาตรี สาขาวิศวกรรมคอมพิวเตอร์ หรือความมั่นคงปลอดภัยไซเบอร์ (Cybersecurity)",
    "skills": ["ความปลอดภัยเครือข่าย", "การตอบสนองต่ออุบัติการณ์", "ระบบปฏิบัติการ"],
    "tools": ["Splunk", "Wireshark", "Nessus"],
    "mode": "หน้างาน (ห้องนิรภัย)",
    "growth": "ขาดแคลนบุคลากรอย่างหนัก",
    "image": "https://tse1.mm.bing.net/th/id/OIP.DQ0MYmTPbuKJmlHytVuI4AHaEO?rs=1&pid=ImgDetMain&o=7&rm=3",
    "reference": "https://www.google.com/search?q=Cyber+Security+Analyst+Career"
  },
  {
    "id": 18,
    "title": "นักทดสอบเจาะระบบ (Penetration Tester)",
    "category": "ความปลอดภัย",
    "icon": "fa-solid fa-user-secret",
    "salary": "60,000 - 150,000",
    "desc": "แฮกเกอร์สายขาว ผู้ทดสอบเจาะระบบเพื่อหาจุดอ่อน",
    "long_desc": "ได้รับอนุญาตให้จำลองการโจมตี (Ethical Hacking) เพื่อหาช่องโหว่ของเว็บไซต์หรือแอปพลิเคชัน ก่อนที่แฮกเกอร์ตัวจริงจะเจอ",
    "responsibilities": ["ทดสอบเจาะระบบ (Pentest)", "เขียนรายงานช่องโหว่", "แนะนำวิธีแก้ไขช่องโหว่"],
    "education": "ปริญญาตรี สาขาวิทยาการคอมพิวเตอร์ หรือเทคโนโลยีสารสนเทศ พร้อมใบประกาศนียบัตรวิชาชีพ (เช่น OSCP)",
    "skills": ["การเจาะระบบอย่างมีจริยธรรม", "การเขียนสคริปต์", "การเขียนรายงานทางเทคนิค"],
    "tools": ["Kali Linux", "Burp Suite", "Metasploit"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "รายได้สูงและเป็นที่ต้องการตัวมาก",
    "image": "https://nextpentest.com/assets/images/about-section-img1.png",
    "reference": "https://www.google.com/search?q=Ethical+Hacking+Certification"
  },

  // --- สุขภาพ ---
  {
    "id": 19,
    "title": "นักพัฒนาเทคโนโลยีสุขภาพ (Health Tech Developer)",
    "category": "สุขภาพ",
    "icon": "fa-solid fa-heart-pulse",
    "salary": "45,000 - 120,000",
    "desc": "นักพัฒนาเทคโนโลยีเพื่อสุขภาพ",
    "long_desc": "สร้างแอปพลิเคชัน Telemedicine ระบบนัดหมอออนไลน์ หรือเชื่อมต่อข้อมูลจาก Smart Watch เข้าสู่ระบบของแพทย์ เพื่อให้การดูแลสุขภาพทั่วถึง",
    "responsibilities": ["พัฒนาแอปสุขภาพ", "เชื่อมต่ออุปกรณ์ IoT (นาฬิกาอัจฉริยะ)", "ดูแลความเป็นส่วนตัวของข้อมูลคนไข้"],
    "education": "ปริญญาตรี สาขาวิศวกรรมชีวการแพทย์ หรือวิทยาการคอมพิวเตอร์",
    "skills": ["การพัฒนาแอปมือถือ", "ความเป็นส่วนตัวของข้อมูล", "มาตรฐานข้อมูลสุขภาพ"],
    "tools": ["Flutter", "HealthKit", "Firebase"],
    "mode": "ทำงานแบบผสมผสาน (Hybrid)",
    "growth": "เติบโตตามสังคมผู้สูงอายุ",
    "image": "https://img.freepik.com/premium-photo/revolutionizing-healthcare-uniting-medicine-genetics-technology-advanced-diagnosis_1000124-210678.jpg",
    "reference": "https://www.google.com/search?q=Health+Tech+Startup+Ideas"
  },
  {
    "id": 20,
    "title": "นักชีวสารสนเทศ (Bioinformatics Scientist)",
    "category": "สุขภาพ",
    "icon": "fa-solid fa-dna",
    "salary": "60,000 - 140,000",
    "desc": "นักชีวสารสนเทศ วิเคราะห์รหัสพันธุกรรมด้วยคอมพิวเตอร์",
    "long_desc": "ใช้ความรู้ด้านชีววิทยาและโปรแกรมมิ่ง เพื่อวิเคราะห์ข้อมูล DNA/RNA ขนาดใหญ่ ช่วยในการคิดค้นยารักษาโรคหรือวัคซีนใหม่ๆ",
    "responsibilities": ["วิเคราะห์ข้อมูลพันธุกรรม", "เขียนสคริปต์ประมวลผล", "ทำแบบจำลองข้อมูลชีวภาพ"],
    "education": "ปริญญาโทหรือปริญญาเอก สาขาชีวสารสนเทศ, ชีววิทยา หรือวิทยาการคอมพิวเตอร์",
    "skills": ["ชีววิทยา", "Python/R", "สถิติ"],
    "tools": ["BLAST", "Biopython", "Linux"],
    "mode": "ห้องปฏิบัติการ หรือ สำนักงาน",
    "growth": "อาชีพเฉพาะทางที่ต้องการสูง",
    "image": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80",
    "reference": "https://www.google.com/search?q=Bioinformatics+Career"
  },
  
  // --- อื่นๆ (อนาคต) ---
  {
    "id": 21,
    "title": "ผู้เชี่ยวชาญ IoT (IoT Specialist)",
    "category": "ซอฟต์แวร์",
    "icon": "fa-solid fa-wifi",
    "salary": "45,000 - 100,000",
    "desc": "ผู้เชี่ยวชาญ Internet of Things เชื่อมอุปกรณ์เข้าสู่เน็ต",
    "long_desc": "ออกแบบระบบ Smart Home หรือ Smart Factory ให้อุปกรณ์ต่างๆ (Sensor, กล้อง, เครื่องจักร) คุยกันได้ผ่านอินเทอร์เน็ต",
    "responsibilities": ["ออกแบบวงจรและเซนเซอร์", "เขียน Firmware", "เชื่อมต่อระบบคลาวด์ MQTT"],
    "education": "ปริญญาตรี สาขาวิศวกรรมอิเล็กทรอนิกส์ หรือวิศวกรรมคอมพิวเตอร์",
    "skills": ["อิเล็กทรอนิกส์", "ไมโครคอนโทรลเลอร์", "ระบบเครือข่าย"],
    "tools": ["Arduino", "Raspberry Pi", "MQTT"],
    "mode": "ปฏิบัติงานหน้างาน หรือ ห้องปฏิบัติการ",
    "growth": "มาแรงในกลุ่มโรงงานอุตสาหกรรม",
    "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    "reference": "https://www.google.com/search?q=IoT+Projects+Examples"
  },
  {
    "id": 22,
    "title": "วิศวกรหุ่นยนต์ (Robotics Engineer)",
    "category": "AI และข้อมูล",
    "icon": "fa-solid fa-hand-holding-hand",
    "salary": "50,000 - 120,000",
    "desc": "วิศวกรหุ่นยนต์ สร้างเครื่องจักรทำงานแทนคน",
    "long_desc": "ออกแบบและโปรแกรมหุ่นยนต์แขนกล (Robot Arm) ในโรงงาน หรือหุ่นยนต์บริการ ให้เคลื่อนที่และทำงานได้อย่างแม่นยำ",
    "responsibilities": ["ออกแบบกลไกหุ่นยนต์", "เขียนโปรแกรมควบคุม (ROS)", "ดูแลรักษาระบบ"],
    "education": "ปริญญาตรี สาขาวิศวกรรมเมคคาทรอนิกส์ หรือวิศวกรรมเครื่องกล",
    "skills": ["กลศาสตร์", "ทฤษฎีการควบคุม", "การเขียนโปรแกรม"],
    "tools": ["ROS", "SolidWorks", "C++"],
    "mode": "ปฏิบัติงานหน้างาน (On-site)",
    "growth": "มีความต้องการสูงในพื้นที่เขตเศรษฐกิจพิเศษ (EEC)",
    "image": "https://cms.skyict.co.th/wp-content/uploads/2024/09/Robotics-Engineer-1.jpg",
    "reference": "https://www.google.com/search?q=Robotics+Engineer+Salary"
  }
];